name: to_do_list
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.1.2
  moor_flutter: ^3.1.0
  simple_animations: ^1.3.3
  shared_preferences:
  flutter_slidable: ^0.5.5
  circular_check_box: ^1.0.2
  flutter_datetime_picker: ^1.4.0
  modal_progress_hud: ^0.1.3
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  enum_to_string: ^1.0.14
  intl: ^0.16.1

dev_dependencies:
  moor_generator: ^3.1.0
  build_runner: ^1.6.7
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
